import redditbot as r

assert r.build_reply("[Sire of Shards] is my favorite item") == None
assert r.build_reply("[Sire of Shards]] is my favorite item") == None
assert r.build_reply("[[]] is my favorite item") == None
assert r.build_reply("[[[Sire of Shards] is my favorite item") == None

#assert r.build_reply("[[]] [[Facebreaker]] [[Cast on crit]]") == None
#assert r.build_reply("[[Sire of Shards]] is my favorite item") == 'Sire of Shards'

item_panel, html = r.get_item_panel("Atziri's Splendour")
assert item_panel == "Atziri's Splendour (Armour, Evasion and Life)"
item_panel, html = r.get_item_panel("Vessel of Vinktar")
assert item_panel == "Vessel of Vinktar (Added Lightning Damage to Attacks)"
item_panel, html = r.get_item_panel("Facebreaker")
assert item_panel == "Facebreaker"
item_panel, html = r.get_item_panel("fvvvbasokeq")
assert item_panel == None and html == None
item_panel, html = r.get_item_panel("")
assert item_panel == None and html == None

assert r.build_reply("[[Sire of Shards]]") == u'[Sire of Shards](http://pathofexile.gamepedia.com/Sire_of_Shards)\n\n>######Sire of Shards[](#break)Serpentine Staff\n>>####Staves\n>>####Physical Damage: **46****\u2013****95**\n>>####Critical Strike Chance: **6.40%**\n>>####Attacks per Second: **1.20**\n>>[](#line)\n>>####Requires Level **49**, **85** Str, **85** Int\n>>[](#line)\n>>#####18% Chance to Block\n>>[](#line)\n>>#####+(15-20) to all Attributes\n>>#####+(5-7)% to all Elemental Resistances\n>>#####(60-100)% increased Projectile Damage\n>>#####20% increased Light Radius\n>>#####Socketed Gems fire 4 additional Projectiles\n>>#####Socketed Gems fire Projectiles in a Nova\n>>[](#line)\n>>*That which was broken may yet break.*\n>>\n\n---\n\n^^Questions? ^^Message ^^/u/ha107642 ^^\u2014 ^^Call ^^wiki ^^pages ^^\\(e.g. ^^items ^^or ^^gems)) ^^with ^^[[NAME]] ^^\u2014 ^^I ^^will ^^only ^^post ^^panels ^^for ^^*unique* ^^items ^^\u2014 ^^[Github](https://github.com/ha107642/RedditPoEBot/)\n'

assert r.build_reply("[[Facebreaker]]") == u'[Facebreaker](http://pathofexile.gamepedia.com/Facebreaker)\n\n>######Facebreaker[](#break)Strapped Mitts\n>>####Evasion: **26**\n>>####Energy Shield: **8**\n>>[](#line)\n>>####Requires Level **16**, **14** Dex, **14** Int\n>>[](#line)\n>>#####+90% to Global Critical Strike Multiplier\n>>#####10% reduced Enemy Stun Threshold\n>>#####(600-800)% more Unarmed Physical Damage\n>>#####Extra gore\n>>[](#line)\n>>*Fly like a Storm Crow, crush like a Rhoa*\n>>\n\n---\n\n^^Questions? ^^Message ^^/u/ha107642 ^^\u2014 ^^Call ^^wiki ^^pages ^^\\(e.g. ^^items ^^or ^^gems)) ^^with ^^[[NAME]] ^^\u2014 ^^I ^^will ^^only ^^post ^^panels ^^for ^^*unique* ^^items ^^\u2014 ^^[Github](https://github.com/ha107642/RedditPoEBot/)\n'

assert r.build_reply("[[Coruscating Elixir]]") == u"[Coruscating Elixir](http://pathofexile.gamepedia.com/Coruscating_Elixir)\n\n>######Coruscating Elixir[](#break)Ruby Flask\n>>####Lasts **4.00** Seconds\n>>####Consumes **30** of **60** Charges on use\n>>#####+50% to Fire Resistance\n>>#####+6% to maximum Fire Resistance\n>>[](#line)\n>>####Requires Level **18**\n>>[](#line)\n>>#####Chaos Damage does not bypass Energy Shield during effect\n>>#####Removes all but one Life on use\n>>#####Removed life is regenerated as Energy Shield over 2 seconds\n>>[](#line)\n>>*Let blood sear in your veins,*\n>>\n>>*Let the pain push outwards and turn away your enemy's blows.*\n>>\n>>[](#line)\n>>####Right click to drink. Can only hold charges while in belt. Refills as you kill monsters.\n\n---\n\n^^Questions? ^^Message ^^/u/ha107642 ^^\u2014 ^^Call ^^wiki ^^pages ^^\\(e.g. ^^items ^^or ^^gems)) ^^with ^^[[NAME]] ^^\u2014 ^^I ^^will ^^only ^^post ^^panels ^^for ^^*unique* ^^items ^^\u2014 ^^[Github](https://github.com/ha107642/RedditPoEBot/)\n"

assert r.build_reply("[[Obliteration]]") == u"[Obliteration](http://pathofexile.gamepedia.com/Obliteration)\n\n>######Obliteration[](#break)Demon's Horn\n>>####Wands\n>>####Physical Damage: **(50 to 56)****\u2013****(128 to 140)**\n>>####Critical Strike Chance: **(10.08% to 10.56%)**\n>>####Attacks per Second: **1.20**\n>>[](#line)\n>>####Requires Level **56**, **179** Int\n>>[](#line)\n>>#####(31-35)% increased Spell Damage\n>>[](#line)\n>>#####Adds (24-30) to (80-92) Physical Damage\n>>#####(26-32)% increased Critical Strike Chance\n>>#####Gain (13-15)% of Physical Damage as Extra Chaos Damage\n>>#####Enemies you Kill have a 20% chance to Explode, dealing a quarter of their maximum Life as Chaos Damage\n>>[](#line)\n>>*We forge order from the world around us*\n>>\n>>*Wielding anarchy and destruction as our tools of genesis.*\n>>\n\n---\n\n^^Questions? ^^Message ^^/u/ha107642 ^^\u2014 ^^Call ^^wiki ^^pages ^^\\(e.g. ^^items ^^or ^^gems)) ^^with ^^[[NAME]] ^^\u2014 ^^I ^^will ^^only ^^post ^^panels ^^for ^^*unique* ^^items ^^\u2014 ^^[Github](https://github.com/ha107642/RedditPoEBot/)\n"

assert r.build_reply("[[Oro's Sacrifice]]") == u"[Oro's Sacrifice](http://pathofexile.gamepedia.com/Oro%27s_Sacrifice)\n\n>######Oro's Sacrifice[](#break)Infernal Sword\n>>####Two Hand Swords\n>>####Elemental Damage: **(425 to 475)\u2013(550 to 600)**\n>>####Critical Strike Chance: **5.00%**\n>>####Attacks per Second: **(1.38 to 1.44)**\n>>[](#line)\n>>####Requires Level **67**, **113** Str, **113** Dex\n>>[](#line)\n>>#####30% increased Accuracy Rating\n>>[](#line)\n>>#####No Physical Damage\n>>#####Adds (425-475) to (550-600) Fire Damage\n>>#####(10-15)% increased Attack Speed\n>>#####20% chance to Ignite\n>>#####10% increased Physical Damage taken\n>>#####10% increased Fire Damage taken\n>>#####Culling Strike against Burning Enemies\n>>#####Gain a Frenzy Charge if an Attack Ignites an Enemy\n>>[](#line)\n>>*Give yourself to the flames and your name*\n>>\n>>*will burn in the minds of men forever.*\n>>\n\n---\n\n^^Questions? ^^Message ^^/u/ha107642 ^^\u2014 ^^Call ^^wiki ^^pages ^^\\(e.g. ^^items ^^or ^^gems)) ^^with ^^[[NAME]] ^^\u2014 ^^I ^^will ^^only ^^post ^^panels ^^for ^^*unique* ^^items ^^\u2014 ^^[Github](https://github.com/ha107642/RedditPoEBot/)\n"
